export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING'

export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const SUBACCOUNT_LOADING = 'SUBACCOUNT_LOADING'
export const SUBACCOUNT_ERROR = 'SUBACCOUNT_ERROR'
export const SUBACCOUNT_SUCCESS = 'SUBACCOUNT_SUCCESS'
