export const LOADING = 'LOADING'
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING'

export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR'
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGOUT = 'LOGOUT'

export const SUBACCOUNT_LOADING = 'SUBACCOUNT_LOADING'
export const SUBACCOUNT_ERROR = 'SUBACCOUNT_ERROR'
export const SUBACCOUNT_SUCCESS = 'SUBACCOUNT_SUCCESS'
export const SUBACCOUNT_GET_FULL_DATA_LOADING = 'SUBACCOUNT_GET_FULL_DATA_LOADING'
export const SUBACCOUNT_GET_FULL_DATA_SUCCESS ='SUBACCOUNT_GET_FULL_DATA_SUCCESS'
export const SUBACCOUNT_GET_FULL_DATA_ERROR = 'SUBACCOUNT_GET_FULL_DATA_ERROR'

export const REPORT_ERROR = 'REPORT_ERROR'
export const REPORT_SUCCESS = 'REPORT_SUCCESS'