export const LOADING = 'LOADING'
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING'

export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR'
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS'

export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGOUT = 'LOGOUT'

export const SUBACCOUNTS_LOADING = 'SUBACCOUNTS_LOADING'
export const SUBACCOUNTS_ERROR = 'SUBACCOUNTS_ERROR'
export const SUBACCOUNTS_SUCCESS = 'SUBACCOUNTS_SUCCESS'

export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING'
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR'
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_ERROR'
export const TRANSACTIONS_PART_SUCCESS = 'TRANSACTIONS_PART_SUCCESS'